id: P008052
initial_creation_type: ocr
source_metadata:
  id: bdr:W20085
  title: སོག་པོ་རྟ་རྫོང་།
  author: ''
  volumes:
    cd6a30dbf5834cb781f8721535d10f8e:
      image_group_id: I1KG18040
      title: ''
      volume_number: 1
      total_pages: 280
ebook_metadata:
  title: སོག་པོ་རྟ་རྫོང་།
  author: ''
  sku: P008052
  cover: cover.jpg
  layers:
  - pagination
